
# 의료비 데이터 전처리 + 탐색적 데이터 분석
- 결측치 처리 --> 이상치 처리 --> EDA(탐색적데이터분석, 라벨이 있는 상태) --> 인코딩 --> 파생변수 / 스케일링 --> 저장

### 라이브러리 불러오기, 데이터 로드

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler

# 한글 폰트 설정
plt.rcParams['font.family']='Malgun Gothic'
plt.rcParams['axes.unicode_minus'] = False

df = pd.read_csv('insurance_missing.csv')
df.head()

    age     sex   bmi  children smoker     region   charges
0  56.0  female  22.7       4.0     no  southwest   3230.92
1  22.0  female  28.2       0.0     no  southeast   1601.92
2  26.0    male   NaN       3.0     no  southeast   4764.30
3  29.0  female  29.1       0.0    yes  northeast  26255.60
4  26.0    male  35.0       0.0     no  northeast   3914.46

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       500 non-null    float64
 1   sex       500 non-null    str
 2   bmi       470 non-null    float64
 3   children  485 non-null    float64
 4   smoker    500 non-null    str
 5   region    480 non-null    str
 6   charges   500 non-null    float64
dtypes: float64(4), str(3)
memory usage: 27.5 KB

In [9]:
df.shape        # shape는 속성이라 ()가 붙지 않는다. 결과는 (행개수, 열개수)

(500, 7)

### 결측치 처리

In [10]:
# 결측치 확인하기
df.isnull().sum()

age          0
sex          0
bmi         30
children    15
smoker       0
region      20
charges      0
dtype: int64

In [11]:
# 결측 비율이 50% 초과 --> 컬럼을 삭제
# 결측치 비율을 알기 위해 평균 구하기
missing_ratio = df.isnull().mean()
missing_ratio

age         0.00
sex         0.00
bmi         0.06
children    0.03
smoker      0.00
region      0.04
charges     0.00
dtype: float64

In [12]:
missing_ratio[missing_ratio > 0.5]

Series([], dtype: float64)

In [13]:
missing_ratio[missing_ratio > 0.02]

bmi         0.06
children    0.03
region      0.04
dtype: float64

In [14]:
type(missing_ratio[missing_ratio > 0.02])

pandas.Series

In [15]:
type(df)

pandas.DataFrame

In [16]:
drop_cols = missing_ratio[missing_ratio > 0.5].index.tolist()

In [ ]:
df.drop(columns=drop_cols)  # df 데이터프레임에서 drop_cols 리스트에 들어 있는 컬럼들을 삭제한 새로운 데이터프레임을 반환

      age     sex   bmi  children smoker     region   charges
0    56.0  female  22.7       4.0     no  southwest   3230.92
1    22.0  female  28.2       0.0     no  southeast   1601.92
2    26.0    male   NaN       3.0     no  southeast   4764.30
3    29.0  female  29.1       0.0    yes  northeast  26255.60
4    26.0    male  35.0       0.0     no  northeast   3914.46
..    ...     ...   ...       ...    ...        ...       ...
495  49.0    male  27.1       0.0     no  southwest   7802.82
496  63.0    male  26.2       1.0     no  northeast   3967.26
497  34.0  female  34.6       2.0     no  southwest   3195.25
498  54.0  female  36.3       0.0     no  northeast   5341.74
499  48.0  female  31.9       3.0     no  northeast   3314.65

[500 rows x 7 columns]

In [ ]:
df.select_dtypes(include='number').columns #  데이터 타입이 'number'(숫자형)인 컬럼만 보여줘.

Index(['age', 'bmi', 'children', 'charges'], dtype='str')

In [20]:
type(df.select_dtypes(include='number').columns)

pandas.Index

In [22]:
num_cols_na =df.select_dtypes(include='number').columns
num_cols_na

Index(['age', 'bmi', 'children', 'charges'], dtype='str')

In [ ]:
num_cols_na[df[num_cols_na].isnull().any()]  # num_cols_na(숫자형 컬럼만 모아 놓은 객체)에서 null이 존재하는 컬럼  다 보여줘. any() :자료형은 중요하지 않음. int, float 상관없이 모두 다

Index(['bmi', 'children'], dtype='str')